# -*- coding: utf-8 -*-
"""export tizimlar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjATmkVSjEWkECaQWsmHkxkkW-dJ9wei
"""

def tashxis(belgi):
  if belgi == "isitma":
    return "Parastamol "
  elif belgi == "bosh og'rig'i":
    return " Trimol iching "
  elif belgi == "Tish og'rig'i":
    return "Kyupen iching "
  else:
    return "shifokorga murojat qiling"
belgi = input("Kasallikni kiriting:  ")
natija=tashxis(belgi)
print(natija)

pip install opencv-python

def Car(year,speed,price):
  if year =="2019" and speed=="220 km/h" and price=="25000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm1=cv2.imread("rasm1.jpeg")
       rasm = cv2_imshow(rasm1)
       return   "Bu mashinamiz BMW  " ,rasm
  elif year =="2010" and speed=="200 km/h" and price=="45000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm2=cv2.imread("rasm2.jpeg")
       rasm = cv2_imshow(rasm2)
       return "Bu mashinamiz Chevrolet  ",rasm
  elif year =="2013" and speed=="180 km/h" and price=="98000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm3=cv2.imread("rasm3.jpeg")
       rasm = cv2_imshow(rasm3)
       return "Bu mashinamiz Kia  ",rasm
  elif year =="2014" and speed=="130 km/h" and price=="78000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm4=cv2.imread("rasm4.jpeg")
       rasm = cv2_imshow(rasm4)
       return "Bu mashinamiz Leksus  ",rasm
  elif  year =="2021" and speed=="180 km/h" and price=="54000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm5=cv2.imread("rasm5.jpeg")
       rasm = cv2_imshow(rasm5)
       return "Bu mashinamiz Jaguar  ", rasm2
  elif year =="2020" and speed=="160 km/h" and price=="65000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm6=cv2.imread("rasm6.jpeg")
       rasm = cv2_imshow(rasm6)
       return "Bu mashinamiz Ferrai  ",rasm
  elif year =="2018" and speed=="400 km/h" and price=="54000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm7=cv2.imread("rasm7.jpeg")
       rasm = cv2_imshow(rasm7)
       return "Bu mashinamiz Maseratti  ",rasm
  elif year =="2017" and speed=="210 km/h" and price=="10000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm8=cv2.imread("rasm8.jpeg")
       rasm = cv2_imshow(rasm8)
       return "Bu mashinamiz Hyundai  ", rasm
  elif year =="2016" and speed=="150 km/h" and price=="20000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm9=cv2.imread("rasm9.jpeg")
       rasm = cv2_imshow(rasm9)
       return "Bu mashinamiz Rolce-Royc  ",rasm
  elif year =="2005" and speed=="540 km/h" and price=="50000$":
       from google.colab.patches import cv2_imshow
       import cv2
       rasm10=cv2.imread("rasm10.jpeg")
       rasm = cv2_imshow(rasm10)
       return "Bu mashinamiz Mercedez-Benz  ",rasm
  else:
       return "Bunday mashina mavjud emas"
speed = input("Tanlagan  mashina tezligini kiriting:")
year = input("Tanlagan  mashina yilini kiriting:")
price = input("Tanlagan  mashina narxini kiriting:")
natija = Car(year,speed,price)
print(natija)